-- Seed 6 weeks of pre-draft challenges (clean, no duplicates)
DELETE FROM challenge_submissions;
DELETE FROM challenges;

-- Week 1 (Jul 9-16)
INSERT INTO challenges (week_number, title, description, questions, opens_at, closes_at) VALUES (1, 'Know Your NFL', 'Match the team to their city.', '[{"q":"Which city do the Packers call home?","options":["Milwaukee","Green Bay","Madison","Lambeau"],"correct":1},{"q":"The Ravens are named after which poem?","options":["The Raven (Poe)","The Road Not Taken (Frost)","The Tyger (Blake)","Invictus (Henley)"],"correct":0},{"q":"What year did the Patriots win their first Super Bowl?","options":["2000","2001","2002","2004"],"correct":2},{"q":"Which NFL team plays at SoFi Stadium?","options":["Raiders","Chargers + Rams","49ers","Seahawks"],"correct":1},{"q":"How many teams are in the NFL?","options":["30","31","32","33"],"correct":2}]'::jsonb, '2026-07-09T00:00:00Z', '2026-07-16T00:00:00Z');

-- Week 2 (Jul 16-23)
INSERT INTO challenges (week_number, title, description, questions, opens_at, closes_at) VALUES (2, 'Fantasy 101', 'Know your scoring.', '[{"q":"In 0.5 PPR, how many points is a reception worth?","options":["0","0.5","1","1.5"],"correct":1},{"q":"A QB throws for 300 yards and 2 TDs. How many fantasy points?","options":["20","22","24","26"],"correct":1},{"q":"Which position typically scores the most fantasy points?","options":["QB","RB","WR","TE"],"correct":0},{"q":"What does FAAB stand for?","options":["Fantasy Allocation Acquisition Budget","Free Agent Acquisition Budget","Fantasy Auction Acquisition Bid","Free Agent Auction Budget"],"correct":1},{"q":"How many starters in a standard lineup?","options":["7","8","9","10"],"correct":2}]'::jsonb, '2026-07-16T00:00:00Z', '2026-07-23T00:00:00Z');

-- Week 3 (Jul 23-30)
INSERT INTO challenges (week_number, title, description, questions, opens_at, closes_at) VALUES (3, 'Who Said That?', 'Match the quote to the legend.', '[{"q":"You play to win the game!","options":["Bill Belichick","Herm Edwards","Peyton Manning","Tom Brady"],"correct":1},{"q":"I am not a role model.","options":["Deion Sanders","Charles Barkley","Michael Jordan","Allen Iverson"],"correct":1},{"q":"Next question.","options":["Bill Belichick","Sean McVay","Andy Reid","Mike Tomlin"],"correct":0},{"q":"They are who we thought they were!","options":["John Madden","Dennis Green","Jim Mora","Jon Gruden"],"correct":1},{"q":"The standard is the standard.","options":["Mike Tomlin","Bill Cowher","Joe Gibbs","Tony Dungy"],"correct":0}]'::jsonb, '2026-07-23T00:00:00Z', '2026-07-30T00:00:00Z');

-- Week 4 (Jul 30 - Aug 6)
INSERT INTO challenges (week_number, title, description, questions, opens_at, closes_at) VALUES (4, 'Draft Strategy', 'You think you know how to draft?', '[{"q":"In a 6-team snake draft, what pick does pick 1 get in round 2?","options":["1","6","12","2"],"correct":1},{"q":"Zero-RB strategy means:","options":["Draft no RBs ever","Draft WRs early, RBs late","Draft only RBs","Draft kickers first"],"correct":1},{"q":"What is the most common draft position for a kicker?","options":["Round 5","Round 10","Round 15","Undrafted"],"correct":2},{"q":"A sleeper is:","options":["A player who sleeps during games","A player drafted later than projected value","A rookie","A player coming off injury"],"correct":1},{"q":"How many WRs can you flex in a standard lineup?","options":["0","1","2","3"],"correct":1}]'::jsonb, '2026-07-30T00:00:00Z', '2026-08-06T00:00:00Z');

-- Week 5 (Aug 6-13)
INSERT INTO challenges (week_number, title, description, questions, opens_at, closes_at) VALUES (5, 'History Buff', 'NFL history trivia.', '[{"q":"Who holds the all-time rushing record?","options":["Barry Sanders","Walter Payton","Emmitt Smith","Jim Brown"],"correct":2},{"q":"Which team has the most Super Bowl wins?","options":["49ers","Cowboys","Steelers","Patriots"],"correct":3},{"q":"The only team to go 16-0 in a regular season?","options":["2007 Patriots","2015 Panthers","2009 Colts","1998 Broncos"],"correct":0},{"q":"Who caught the Immaculate Reception?","options":["Lynn Swann","John Stallworth","Franco Harris","Terry Bradshaw"],"correct":2},{"q":"What was the AFL?","options":["American Football League","Atlantic Football League","Alternate Football League","Army Football League"],"correct":0}]'::jsonb, '2026-08-06T00:00:00Z', '2026-08-13T00:00:00Z');

-- Week 6 (Aug 13-20): Chaos Preview
INSERT INTO challenges (week_number, title, description, questions, opens_at, closes_at) VALUES (6, 'Chaos Preview', 'How well do you know the chaos rules?', '[{"q":"What is the Clown Car threshold?","options":["10 pts","15 pts","20 pts","25 pts"],"correct":2},{"q":"The Hex gives how many bonus points?","options":["1","2","3","5"],"correct":2},{"q":"How many consecutive losses before you get renamed?","options":["2","3","4","5"],"correct":1},{"q":"What happens to morale when you lose by 30+?","options":["-5","-10","-15","-20"],"correct":2},{"q":"Steal-a-Player steals from:","options":["Any team","The highest scorer","The team that beat them","The waiver wire"],"correct":1}]'::jsonb, '2026-08-13T00:00:00Z', '2026-08-20T00:00:00Z');
